markdown: rdiscount 
permalink: /:year/:month/:title 
title: 刘思喆@贝吉塔行星
url: http://bjt.name
subscribe: http://bjt.name/feed/
exclude: [ README.md, newpost.rb ]
domain: www.bjt.name
author: bjt
email: sunbjt@gmail.com
auto: true
twitterID: sunbjt
duoshuoShortname: sunbjt
